version: '3.8'

services:
  numerology-ai:
    build: .
    ports:
      - "5173:5173"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=production
    restart: unless-stopped
    expose:
      - "5173"
